heat_template_version: 2013-05-23

description: Template for ACC lab 3

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: 4957f15b-e1c9-453e-8940-ca0b10a629c3
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: ACCHT18.normal
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: ptr
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach instance to.
    default: SNIC 2018/10-30 Internal IPv4 Network

resources:

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }
      
  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - network: { get_param: public_network }

outputs:
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }